# theme: jekyll-theme-slate
remote_theme: nielsenramon/chalk
title: I ❤️ content design
# description: We love writing.
# logo: cdesign.png
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
