theme: jekyll-theme-minimal
title: Resources for content designers
# description: [A short description of your site's purpose]
logo: ../images/cdesign.png
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
